from .models import Recipe


recipe_items = [

    Recipe(
        menu_id=1,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=1,
        inventory_id=4,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=1,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=1,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=2,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=2,
        inventory_id=2,
        quantity_required=0.15
    ),
    Recipe(
        menu_id=2,
        inventory_id=4,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=2,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=2,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=3,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=3,
        inventory_id=2,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=3,
        inventory_id=4,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=3,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=3,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=4,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=4,
        inventory_id=4,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=4,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=4,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=5,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=5,
        inventory_id=2,
        quantity_required=0.15
    ),
    Recipe(
        menu_id=5,
        inventory_id=5,
        quantity_required=0.025
    ),
    Recipe(
        menu_id=5,
        inventory_id=4,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=5,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=5,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=6,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=6,
        inventory_id=2,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=6,
        inventory_id=7,
        quantity_required=0.025
    ),
    Recipe(
        menu_id=6,
        inventory_id=4,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=6,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=6,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=7,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=7,
        inventory_id=2,
        quantity_required=0.16
    ),
    Recipe(
        menu_id=7,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=7,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=8,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=8,
        inventory_id=2,
        quantity_required=0.03
    ),
    Recipe(
        menu_id=8,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=8,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=9,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=9,
        inventory_id=2,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=9,
        inventory_id=4,
        quantity_required=0.01
    ),
    Recipe(
        menu_id=9,
        inventory_id=10,
        quantity_required=0.15
    ),
    Recipe(
        menu_id=9,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=9,
        inventory_id=19,
        quantity_required=1
    ),
    Recipe(
        menu_id=9,
        inventory_id=20,
        quantity_required=1
    ),

    Recipe(
        menu_id=10,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=10,
        inventory_id=2,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=10,
        inventory_id=10,
        quantity_required=0.15
    ),
    Recipe(
        menu_id=10,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=10,
        inventory_id=19,
        quantity_required=1
    ),
    Recipe(
        menu_id=10,
        inventory_id=20,
        quantity_required=1
    ),

    Recipe(
        menu_id=11,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=11,
        inventory_id=10,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=11,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=11,
        inventory_id=19,
        quantity_required=1
    ),
    Recipe(
        menu_id=11,
        inventory_id=20,
        quantity_required=1
    ),

    Recipe(
        menu_id=12,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=12,
        inventory_id=2,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=12,
        inventory_id=5,
        quantity_required=0.03
    ),
    Recipe(
        menu_id=12,
        inventory_id=10,
        quantity_required=0.15
    ),
    Recipe(
        menu_id=12,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=12,
        inventory_id=19,
        quantity_required=1
    ),
    Recipe(
        menu_id=12,
        inventory_id=20,
        quantity_required=1
    ),

    Recipe(
        menu_id=13,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=13,
        inventory_id=2,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=13,
        inventory_id=7,
        quantity_required=0.03
    ),
    Recipe(
        menu_id=13,
        inventory_id=10,
        quantity_required=0.15
    ),
    Recipe(
        menu_id=13,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=13,
        inventory_id=19,
        quantity_required=1
    ),
    Recipe(
        menu_id=13,
        inventory_id=20,
        quantity_required=1
    ),

    Recipe(
        menu_id=14,
        inventory_id=1,
        quantity_required=0.018
    ),
    Recipe(
        menu_id=14,
        inventory_id=2,
        quantity_required=0.20
    ),
    Recipe(
        menu_id=14,
        inventory_id=3,
        quantity_required=0.04
    ),
    Recipe(
        menu_id=14,
        inventory_id=10,
        quantity_required=0.15
    ),
    Recipe(
        menu_id=14,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=14,
        inventory_id=19,
        quantity_required=1
    ),
    Recipe(
        menu_id=14,
        inventory_id=20,
        quantity_required=1
    ),

    Recipe(
        menu_id=15,
        inventory_id=8,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=15,
        inventory_id=4,
        quantity_required=0.005
    ),
    Recipe(
        menu_id=15,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=15,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=16,
        inventory_id=9,
        quantity_required=0.008
    ),
    Recipe(
        menu_id=16,
        inventory_id=2,
        quantity_required=0.10
    ),
    Recipe(
        menu_id=16,
        inventory_id=4,
        quantity_required=0.008
    ),
    Recipe(
        menu_id=16,
        inventory_id=18,
        quantity_required=1
    ),
    Recipe(
        menu_id=16,
        inventory_id=19,
        quantity_required=1
    ),

    Recipe(
        menu_id=17,
        inventory_id=11,
        quantity_required=0.10
    ),
    Recipe(
        menu_id=17,
        inventory_id=12,
        quantity_required=0.05
    ),
    Recipe(
        menu_id=17,
        inventory_id=13,
        quantity_required=0.01
    ),
    Recipe(
        menu_id=17,
        inventory_id=21,
        quantity_required=1
    ),

    Recipe(
        menu_id=18,
        inventory_id=11,
        quantity_required=0.10
    ),
    Recipe(
        menu_id=18,
        inventory_id=12,
        quantity_required=0.05
    ),
    Recipe(
        menu_id=18,
        inventory_id=14,
        quantity_required=0.04
    ),
    Recipe(
        menu_id=18,
        inventory_id=13,
        quantity_required=0.01
    ),
    Recipe(
        menu_id=18,
        inventory_id=21,
        quantity_required=1
    ),

    Recipe(
        menu_id=19,
        inventory_id=11,
        quantity_required=0.10
    ),
    Recipe(
        menu_id=19,
        inventory_id=12,
        quantity_required=0.05
    ),
    Recipe(
        menu_id=19,
        inventory_id=14,
        quantity_required=0.03
    ),
    Recipe(
        menu_id=19,
        inventory_id=15,
        quantity_required=0.03
    ),
    Recipe(
        menu_id=19,
        inventory_id=13,
        quantity_required=0.01
    ),
    Recipe(
        menu_id=19,
        inventory_id=21,
        quantity_required=1
    ),

    Recipe(
        menu_id=20,
        inventory_id=11,
        quantity_required=0.10
    ),
    Recipe(
        menu_id=20,
        inventory_id=12,
        quantity_required=0.05
    ),
    Recipe(
        menu_id=20,
        inventory_id=15,
        quantity_required=0.04
    ),
    Recipe(
        menu_id=20,
        inventory_id=13,
        quantity_required=0.01
    ),
    Recipe(
        menu_id=20,
        inventory_id=21,
        quantity_required=1
    ),

    Recipe(
        menu_id=21,
        inventory_id=16,
        quantity_required=1
    ),
    Recipe(
        menu_id=21,
        inventory_id=21,
        quantity_required=1
    ),

    Recipe(
        menu_id=22,
        inventory_id=17,
        quantity_required=1
    ),
    Recipe(
        menu_id=22,
        inventory_id=21,
        quantity_required=1
    ),

    Recipe(
        menu_id=23,
        inventory_id=16,
        quantity_required=1
    ),
    Recipe(
        menu_id=23,
        inventory_id=3,
        quantity_required=0.04
    ),
    Recipe(
        menu_id=23,
        inventory_id=21,
        quantity_required=1
    ),
]

